# Generated by Django 5.0.6 on 2024-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MsgID', models.CharField(max_length=50)),
                ('SessionGUID', models.CharField(max_length=128)),
                ('eTXPatientGUID', models.CharField(max_length=128)),
                ('MsgFrom', models.CharField(max_length=20)),
                ('MsgTo', models.CharField(max_length=20)),
                ('SourceType', models.CharField(max_length=50)),
                ('MsgText', models.CharField(max_length=1600)),
                ('DocMIMEType', models.CharField(blank=True, max_length=255, null=True)),
                ('DocSize', models.FloatField(blank=True, null=True)),
                ('DocURL', models.CharField(blank=True, max_length=255, null=True)),
                ('DocBLOB', models.BinaryField(blank=True, null=True)),
                ('Direction', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('ReadStatus', models.IntegerField()),
                ('MsgHistory', models.TextField(blank=True, null=True)),
                ('IntegrationFlag', models.IntegerField()),
                ('IsDeleted', models.IntegerField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField()),
                ('LastUpdatedBy', models.CharField(max_length=50)),
                ('LastUpdatedDate', models.DateTimeField()),
            ],
        ),
    ]
