# Generated by Django 5.0.6 on 2024-06-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_meessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meessage',
            new_name='Message',
        ),
    ]
